exports={
intervals: [
                 { semitones: 0, name: "root"},
                 { semitones: 1, name: "m2"},
                 { semitones: 2, name: "M2"},
                 { semitones: 3, name: "m3"},
                 { semitones: 4, name: "M3"},
                 { semitones: 5, name: "P4"},
                 { semitones: 6, name: "b5"},
                 { semitones: 7, name: "P5"},
                 { semitones: 8, name: "m6"},
                 { semitones: 9, name: "M6"},
                 { semitones: 10, name: "m7"},
                 { semitones: 11, name: "M7"}
                ],
notes: [
             { id: 1, name: "A", alias: "A"},
             { id: 2, name: "A#", alias: "Bb"},
             { id: 3, name: "B", alias: "B"},
             { id: 4, name: "C", alias: "C"},
             { id: 5, name: "C#", alias: "Db"},
             { id: 6, name: "D", alias: "D"},
             { id: 7, name: "D#", alias: "Eb"},
             { id: 8, name: "E", alias: "E"},
             { id: 9, name: "F", alias: "F"},
             { id: 10, name: "F#", alias: "Gb"},
             { id: 11, name: "G", alias: "G"},
             { id: 12, name: "G#", alias: "Ab"}
            ],

chords: [
        { name: "Major", intervals: [4,7]},
        { name: "Minor", intervals: [3,7]},
        { name: "Augmented", intervals: [4,8]},
        { name: "Dimished", intervals: [3,6]},
        { name: "7", intervals: [4,7,10]},
        { name: "M7", intervals: [4,7,11]},
        { name: "sus2", intervals: [2,7]},
        { name: "sus4", intervals: [5,7]},
        { name: "6", intervals: [4,7,9]},
        { name: "6/9", intervals: [4,7,9,2]},
        { name: "M13", intervals: [4,7,11,2,9]},
        { name: "M9", intervals: [4,7,11,2]},
        { name: "M9#11", intervals: [4,7,11,2,6]},
        { name: "M7+", intervals: [4,8,11]},
        { name: "M7b5", intervals: [4,6,11]},
        { name: "M13(no9)", intervals: [4,7,11,9]},
        { name: "add9", intervals: [4,7,2]},
        { name: "m7", intervals: [3,7,10]},
        { name: "m6", intervals: [3,7,9]},
        { name: "m(M7)", intervals: [3,7,11]},
        { name: "m(add9)", intervals: [3,7,2]},
        { name: "m9", intervals: [3,7,10,2]},
        { name: "m(M9)", intervals: [3,7,11,2]},
        { name: "m 6/9", intervals: [3,7,9,2]},
        { name: "m11", intervals: [3,7,10,2,5]},
        { name: "m11(no9)", intervals: [3,7,10,5]},
        { name: "9", intervals: [4,7,10,2]},
        { name: "13", intervals: [4,7,10,2,9]},
        { name: "7b9", intervals: [4,7,10,1]},
        { name: "7#9", intervals: [4,7,10,3]},
        { name: "7+", intervals: [4,8,10]},
        { name: "13b9", intervals: [4,7,10,1,9]},
        { name: "7b5", intervals: [4,6,10]},
        { name: "7b9/#5", intervals: [4,8,10,1]},
        { name: "7#9/#5", intervals: [4,8,10,3]},
        { name: "9#11", intervals: [4,7,10,2,6]},
        { name: "9+", intervals: [4,8,10,2]},
        { name: "7sus4", intervals: [5,7,10]},
        { name: "9sus4", intervals: [5,7,10,2]},
        { name: "13sus4", intervals: [5,7,10,2,9]},
        { name: "m7b5", intervals: [3,6,10]},
        { name: "dim7", intervals: [3,6,9]},
            { name: "Ionian", intervals: [2,4,5,7,9,11]},
            { name: "Dorian", intervals: [2,3,5,7,9,10]},
            { name: "Phrygian", intervals: [1,3,5,7,8,10]},
            { name: "Lydian", intervals: [2,4,6,7,9,11]},
            { name: "Mixolydian", intervals: [2,4,5,7,9,10]},
            { name: "Aeolian", intervals: [2,3,5,7,8,10]},
            { name: "Locrian", intervals: [1,3,5,6,8,10]},
            { name: "Major Pentatonic", intervals: [2,4,7,9]},
            { name: "Minor Pentatonic", intervals: [3,5,7,10]},
            { name: "Harmonic Minor", intervals: [2,3,5,7,8,11]},
            { name: "Jazz Melodic Minor", intervals: [2,3,5,7,9,11]},
            { name: "Lydian Flat-Seven", intervals: [2,4,6,7,9,10]},
            { name: "Whole Tone", intervals: [2,4,6,8,10]},
            { name: "Diminished (whole-half)", intervals: [2,3,5,6,8,9,11]},
            { name: "Blues Scale (w/M3+b5)", intervals: [3,4,5,6,7,10]}
         ],
tunings: [
          { name: "standard", notes: [8,3,11,6,1,8]},
          { name: "dropd", notes: [8,3,11,6,1,6]},
          { name: "dadgad", notes: [6,1,11,6,1,6]}
         ]
}
